### ISSUE TITLE
Energy Repair/Psi Repair not working

### ISSUE THREAD

**Issue by Gawdin** [Bartz24/MoarTinkers#16]
I'm using Moar Tinkers 0.5.4 on Minecraft 1.12.2 using the All The Mods 3 modpack (version 5.2). The most recent update added PlusTiC to it (I am not sure if this is what caused the issue). Prior to the latest update, Energy Repair and Psi Repair were working normally (using energy cells from TE). However, it no longer seems to work at all anymore. I even tried this on a clean world. The only mods I was running in addition to ATM3 that were updated were Creativecore and Bonsai Trees. So I don't think they had anything to do with it. I also tried with a powercell (both advanced and creative) from RFTools which didn't work either.

**Comment by Bartz24** [comment]
it might be that AllTheMods is using plustic materials over moar tinkers, meaning they might have different traits

what traits are listed under your tool?

if you don't have the world still, it's fine, but issues arise when similar mods are in the same pack

**Comment by TakunSho** [comment]
Yeah, I totally forgot about this issue because of real life issues. I do recall isolating it to an interaction with PlusTiC yes. I found this out later when I was trying to use the Psimetal/Psigem from PlusTiC and the Ebony/Ivory from MoarTinkers. They don't seem to like playing together with Psi specifically. Now if I turn Psi's mats off for one or the other, then it works fine again. But as you gathered, I don't have the world anymore and I haven't gotten to Psi yet on my current modpack to see if it is still an issue after all the new updates.
