### ISSUE TITLE
Incompatibility With Tinkers Addon Pewter

### ISSUE THREAD

**Issue by UnlimatedStone9** [Bartz24/MoarTinkers#40]
I got a crash report upon launching Moar Tinkers with Pewter, Both mods register some of the same materials like mana steel so its an incompatibility issue, is it possible this mods use of those items is disabled when Pewter is installed or if it would force disable Pewters, Thanks!         -UnlimatedStone9

Crash Report: https://pastebin.com/nFAim5vN

**Comment by Bartz24** [comment]
that's because pewter isn't detecting that manasteel is already registered. It's technically not moar tinkers fault, but check the config of both mods.

if pewter doesn't have one to disable the materials, then disable it on moar tinkers.

I did all I could to avoid crashes, but other mods need to do the same

**Comment by UnlimatedStone9** [comment]
When the crash occurred and I checked the configs pewters was entirely empty

**Comment by UnlimatedStone9** [comment]
not too important anyways, Ill look in to it on my end and check with the Pewter devs in future if any errors arise
